In [2]:
import numpy as np

In [10]:
c=np.array([[[{"min temp":12,"max temp":32},{"min temp":13,"max temp":25},{"min temp":7,"max temp":26},{"min temp":8,"max temp":26}]]])

In [9]:
c

array([[[{'min temp': 12, 'max temp': 32},
         {'min temp': 13, 'max temp': 25},
         {'min temp': 7, 'max temp': 26},
         {'min temp': 8, 'max temp': 26}]]], dtype=object)

In [2]:
a=np.arange(1,225)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [4]:
a=np.reshape(a,(4,4,7,2))

In [5]:
a

array([[[[  1,   2],
         [  3,   4],
         [  5,   6],
         [  7,   8],
         [  9,  10],
         [ 11,  12],
         [ 13,  14]],

        [[ 15,  16],
         [ 17,  18],
         [ 19,  20],
         [ 21,  22],
         [ 23,  24],
         [ 25,  26],
         [ 27,  28]],

        [[ 29,  30],
         [ 31,  32],
         [ 33,  34],
         [ 35,  36],
         [ 37,  38],
         [ 39,  40],
         [ 41,  42]],

        [[ 43,  44],
         [ 45,  46],
         [ 47,  48],
         [ 49,  50],
         [ 51,  52],
         [ 53,  54],
         [ 55,  56]]],


       [[[ 57,  58],
         [ 59,  60],
         [ 61,  62],
         [ 63,  64],
         [ 65,  66],
         [ 67,  68],
         [ 69,  70]],

        [[ 71,  72],
         [ 73,  74],
         [ 75,  76],
         [ 77,  78],
         [ 79,  80],
         [ 81,  82],
         [ 83,  84]],

        [[ 85,  86],
         [ 87,  88],
         [ 89,  90],
         [ 91,  92],
         [ 93,  94],

In [17]:
ex=np.array([[[[ 10,  16],
                 [  8,  20],
                 [ 15,  20],
                 [ 15,  29],
                 [  9,  28],
                 [ 11,  26],
                 [ 10,  29]],

                [[ 13,  25],
                 [ 10,  20],
                 [ 14,  26],
                 [-13,  27],
                 [  9,  32],
                 [ 11,  30],
                 [ 14,  20]],

                [[  7,  26],
                 [  8,  27],
                 [  8,  24],
                 [  8,  25],
                 [ 12,  25],
                 [ 13,  30],
                 [  7,  20]],

                [[  8,  26],
                 [ 15,  20],
                 [ 15,  28],
                 [ 13,  21],
                 [  9,  28],
                 [  7,  30],
                 [  8,  28]]],


               [[[ 12,  24],
                 [ 13,  25],
                 [ 11,  31],
                 [  9,  32],
                 [ 15,  21],
                 [ 11,  22],
                 [  7,  31]],

                [[ 12,  29],
                 [  7,  22],
                 [ 11,  25],
                 [  9,  21],
                 [ 15,  20],
                 [  8,  30],
                 [  7,  28]],

                [[ 12,  21],
                 [  9,  27],
                 [  7,  21],
                 [  8,  22],
                 [ 12,  21],
                 [ 11,  31],
                 [  8,  25]],

                [[  9,  26],
                 [ 15,  25],
                 [ 10,  30],
                 [ 11,  32],
                 [ 12,  30],
                 [ 14,  23],
                 [  7,  27]]],


               [[[  1,  20],
                 [  3,  20],
                 [  5,  21],
                 [  4,  18],
                 [  2,  21],
                 [  5,   5],
                 [ 19,   6]],

                [[  5,  20],
                 [  2,  22],
                 [  7,  18],
                 [  4,  22],
                 [  6,  22],
                 [  5,   5],
                 [ 22,   6]],

                [[  8,  18],
                 [  8,  21],
                 [  7,  19],
                 [  5,  18],
                 [  5,  20],
                 [  3,   7],
                 [ 19,   7]],

                [[  6,  19],
                 [  3,  20],
                 [  5,  21],
                 [  2,  20],
                 [  3,  22],
                 [  8,   5],
                 [ 21,   7]]],


               [[[  9,  21],
                 [  8,  22],
                 [-10,  19],
                 [  9,  22],
                 [ 12,  18],
                 [ 12,  71],
                 [ 18,  12]],

                [[ 12,  19],
                 [ 12,  20],
                 [ 12,  18],
                 [ 12,  20],
                 [ 12,  20],
                 [ 11,   8],
                 [ 18,  10]],

                [[  8,  19],
                 [ 11,  22],
                 [  9,  18],
                 [  8,  18],
                 [  9,  20],
                 [  7,   8],
                 [ 18,   7]],

                [[  8,  18],
                 [ 11,  18],
                 [  9,  21],
                 [ 11,  20],
                 [  9,  22],
                 [  8,   9],
                 [ 19,  12]]]])
           

In [15]:
temp=np.array([[[[7,29],[6,29],[6,25],[14,21],[10,28],[15,21],[14,20]],[[10,26],[13,32],[6,29],[-13,25],[7,31],[14,29],[12,31]],[[15,23],[12,25],[8,30],[8,31],[15,27],[12,27],[6,20]],[[6,29],[6,28],[7,32],[7,32],[14,32],[13,21],[14,25]]],[[[15,30],[9,20],[15,27],[15,23],[7,23],[15,30],[13,27]],[[9,28],[14,20],[6,21],[14,25],[11,21],[14,21],[10,20]],[[7,28],[6,27],[11,27],[11,20],[13,22],[15,20],[13,27]],[[11,23],[11,26],[11,21],[15,26],[9,21],[12,31],[6,24]]],[[[5,19],[7,19],[8,20],[6,19],[3,21],[5,7],[19,2]],[[4,22],[5,20],[6,20],[3,22],[6,18],[5,2],[18,3]],[[7,19],[5,22],[4,21],[8,21],[8,21],[2,3],[21,5]],[[5,21],[7,20],[2,19],[7,21],[4,18],[8,3],[21,8]]]
,[[[7,22],[9,22],[-10,19],[8,19],[12,20],[11,71],[21,7]],[[7,18],[11,19],[7,18],[8,18],[11,18],[11,7],[21,8]],[[10,19],[12,20],[7,21],[12,21],[8,18],[9,8],[21,9]],[[10,22],[8,19],[7,19],[12,20],[11,20],[12,8],[19,7]]]])

In [16]:
#q1
temp

array([[[[  7,  29],
         [  6,  29],
         [  6,  25],
         [ 14,  21],
         [ 10,  28],
         [ 15,  21],
         [ 14,  20]],

        [[ 10,  26],
         [ 13,  32],
         [  6,  29],
         [-13,  25],
         [  7,  31],
         [ 14,  29],
         [ 12,  31]],

        [[ 15,  23],
         [ 12,  25],
         [  8,  30],
         [  8,  31],
         [ 15,  27],
         [ 12,  27],
         [  6,  20]],

        [[  6,  29],
         [  6,  28],
         [  7,  32],
         [  7,  32],
         [ 14,  32],
         [ 13,  21],
         [ 14,  25]]],


       [[[ 15,  30],
         [  9,  20],
         [ 15,  27],
         [ 15,  23],
         [  7,  23],
         [ 15,  30],
         [ 13,  27]],

        [[  9,  28],
         [ 14,  20],
         [  6,  21],
         [ 14,  25],
         [ 11,  21],
         [ 14,  21],
         [ 10,  20]],

        [[  7,  28],
         [  6,  27],
         [ 11,  27],
         [ 11,  20],
         [ 13,  22],

In [20]:
#q2a
temp.shape

(4, 4, 7, 2)

In [21]:
#q2b
temp.ndim

4

In [18]:
#q3 Print the daily temperatures for the first week of each month.
temp[:,:1]

array([[[[  7,  29],
         [  6,  29],
         [  6,  25],
         [ 14,  21],
         [ 10,  28],
         [ 15,  21],
         [ 14,  20]]],


       [[[ 15,  30],
         [  9,  20],
         [ 15,  27],
         [ 15,  23],
         [  7,  23],
         [ 15,  30],
         [ 13,  27]]],


       [[[  5,  19],
         [  7,  19],
         [  8,  20],
         [  6,  19],
         [  3,  21],
         [  5,   7],
         [ 19,   2]]],


       [[[  7,  22],
         [  9,  22],
         [-10,  19],
         [  8,  19],
         [ 12,  20],
         [ 11,  71],
         [ 21,   7]]]])

In [8]:
#q4 Print the temperatures for Tuesday of each month
temp[:,:,1:2,:]

array([[[[ 8, 20]],

        [[10, 20]],

        [[ 8, 27]],

        [[15, 20]]],


       [[[13, 25]],

        [[ 7, 22]],

        [[ 9, 27]],

        [[15, 25]]],


       [[[ 3, 20]],

        [[ 2, 22]],

        [[ 8, 21]],

        [[ 3, 20]]],


       [[[ 8, 22]],

        [[12, 20]],

        [[11, 22]],

        [[11, 18]]]])

In [19]:
#q5 Print only the maximum temperature for all the weekdays of Dec and Feb.
temp[1::2,:,:,1:]

array([[[[30],
         [20],
         [27],
         [23],
         [23],
         [30],
         [27]],

        [[28],
         [20],
         [21],
         [25],
         [21],
         [21],
         [20]],

        [[28],
         [27],
         [27],
         [20],
         [22],
         [20],
         [27]],

        [[23],
         [26],
         [21],
         [26],
         [21],
         [31],
         [24]]],


       [[[22],
         [22],
         [19],
         [19],
         [20],
         [71],
         [ 7]],

        [[18],
         [19],
         [18],
         [18],
         [18],
         [ 7],
         [ 8]],

        [[19],
         [20],
         [21],
         [21],
         [18],
         [ 8],
         [ 9]],

        [[22],
         [19],
         [19],
         [20],
         [20],
         [ 8],
         [ 7]]]])

In [22]:
#q6 Print all the days along with the week number in November when the minimum temperature was less than 8 degrees
for i in range (0,4):
    y=f[0,i:i+1,0:7,0:1]
    z=f[0,i:i+1,0:7,0:1]<8
    print("Week no. is: ",i+1)
    print(y[z])

Week no. is:  1
[7 6 6]
Week no. is:  2
[  6 -13   7]
Week no. is:  3
[6]
Week no. is:  4
[6 6 7 7]


In [24]:
#q7 Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.

for i in range (0,4):
    y=f[1:4:2,i:i+1,0:7,1:2]
    z=f[1:4:2,i:i+1,0:7,1:2]>20
    print("Week no. is: ",i+1)
    print(y[z])

Week no. is:  1
[30 27 23 23 30 27 22 22 71]
Week no. is:  2
[28 21 25 21 21]
Week no. is:  3
[28 27 27 22 27 21 21]
Week no. is:  4
[23 26 21 26 21 31 24 22]


In [47]:
 #q8 Check if there are any absurd values present in the dataset
q1 = np.percentile(temp, 25)
q3 = np.percentile(temp, 75)
iqr = q3 - q1
threshold = 1.5 * iqr
outliers = np.where((temp < q1 - threshold) | (temp > q3 + threshold))
 
print("Outliers of array is : \n", temp[outliers])

Outliers of array is : 
 []


In [46]:
#q10 Find and print the indexes of all the outlier(unusual) values present in the above dataset.
outliers


(array([0, 3], dtype=int64),
 array([1, 0], dtype=int64),
 array([3, 5], dtype=int64),
 array([0, 1], dtype=int64))

In [ ]:
#q11 Replace the outliers with an appropriate value.
temp[0,1,3,0]=15
temp[3,0,5,1]=30
print(temp)

In [24]:
#q12 Find the average max temperature for the winter months in Jaipur.
b=np.average(temp[:,:,:,1:])
np.round(b,decimals=2)

21.57

In [4]:
#q13 Find the weekly min avg temp for the month of Dec in Jaipur
a=np.mean(temp[1::4,0:1,:,0::2])
a=np.round(a,decimals=2)
b=np.mean(temp[1::4,1:2,:,0::2])
b=np.round(b,decimals=2)
c=np.mean(temp[1::4,2:3,:,0::2])
c=np.round(c,decimals=2)
d=np.mean(temp[1::4,3:4,:,0::2])
d=np.round(d,decimals=2)
print(a,"",b,"",c,"",d)

11.14  9.86  9.57  11.14


In [9]:
#q14 Find the overall avg temp for the months Dec and Jan

b=np.average(temp[1:3,:,:,:])
np.round(b,decimals=2)


14.8

In [41]:

#15.Find the least temp experienced by the city in the month of Dec and Jan. Also print the exact date( Day/Week/Month) for the same.
mindec = np.min(temp[1])
minjan = np.min(temp[2])
c = np.where(temp[1]==mindec)
print(c)
print("december : ")
for i,n in zip(c[0],c[1]):
  print(f'week: {i+1} day: {n+1} ', mindec)

d = np.where(temp[2]==mindec)
print(d)
print("janurary : ")
for i,n in zip(d[0],d[1]):
    print(f'week: {i+1} day: {n+1} ', minjan)


(array([1, 2, 3], dtype=int64), array([2, 1, 6], dtype=int64), array([0, 0, 0], dtype=int64))
december : 
week: 2 day: 3  6
week: 3 day: 2  6
week: 4 day: 7  6
(array([0, 1, 1], dtype=int64), array([3, 2, 4], dtype=int64), array([0, 0, 0], dtype=int64))
janurary : 
week: 1 day: 4  2
week: 2 day: 3  2
week: 2 day: 5  2


In [42]:
#16 Find the max temp in the month of Feb and return its date(Day/Week/Month)
maxfeb = np.max(temp[3])
c=np.where(temp[3]==maxfeb)
print('max temp in feb = ', maxfeb)
print(c)
for i , n in zip(c[0],c[1]):
    print(f'feb: Week{i+1}, day{n+1} : ',maxfeb)

max temp in feb =  30
(array([0], dtype=int64), array([5], dtype=int64), array([1], dtype=int64))
feb: Week1, day6 :  30


In [39]:
#q17 Find the days in the month of Nov where the max temp of the day dropped below the avg temp of the month.
b=np.average(temp[0::4])
c=np.round(b,decimals=2)
print("average temp of november is:",c)
d=np.where(temp[0::4,:,:,1:]<c)
print(d)

average temp of november is: 17.5
(array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))


In [48]:
#18 Convert the above dataset into an array where the weeks of the same 
#month must be present in the same row, but belonging to different months
#should come in a row either below or above the selected month
np.reshape(temp,(4,56))

array([[ 10,  16,   8,  20,  15,  20,  15,  29,   9,  28,  11,  26,  10,
         29,  13,  25,  10,  20,  14,  26, -13,  27,   9,  32,  11,  30,
         14,  20,   7,  26,   8,  27,   8,  24,   8,  25,  12,  25,  13,
         30,   7,  20,   8,  26,  15,  20,  15,  28,  13,  21,   9,  28,
          7,  30,   8,  28],
       [ 12,  24,  13,  25,  11,  31,   9,  32,  15,  21,  11,  22,   7,
         31,  12,  29,   7,  22,  11,  25,   9,  21,  15,  20,   8,  30,
          7,  28,  12,  21,   9,  27,   7,  21,   8,  22,  12,  21,  11,
         31,   8,  25,   9,  26,  15,  25,  10,  30,  11,  32,  12,  30,
         14,  23,   7,  27],
       [  1,  20,   3,  20,   5,  21,   4,  18,   2,  21,   5,   5,  19,
          6,   5,  20,   2,  22,   7,  18,   4,  22,   6,  22,   5,   5,
         22,   6,   8,  18,   8,  21,   7,  19,   5,  18,   5,  20,   3,
          7,  19,   7,   6,  19,   3,  20,   5,  21,   2,  20,   3,  22,
          8,   5,  21,   7],
       [  9,  21,   8,  22, -10,  19,

In [43]:
#q19 The above data is appropriate for an audience who follow the metric system of measurement. Create an array that holds the same data but presented in Fahrenheit.
cel=np.array(temp)
feh=((9*cel/5)+32)
print("temperature in fahrenheit is:\n",feh)

temperature in fahrenheit is:
 [[[[44.6 84.2]
   [42.8 84.2]
   [42.8 77. ]
   [57.2 69.8]
   [50.  82.4]
   [59.  69.8]
   [57.2 68. ]]

  [[50.  78.8]
   [55.4 89.6]
   [42.8 84.2]
   [59.  77. ]
   [44.6 87.8]
   [57.2 84.2]
   [53.6 87.8]]

  [[59.  73.4]
   [53.6 77. ]
   [46.4 86. ]
   [46.4 87.8]
   [59.  80.6]
   [53.6 80.6]
   [42.8 68. ]]

  [[42.8 84.2]
   [42.8 82.4]
   [44.6 89.6]
   [44.6 89.6]
   [57.2 89.6]
   [55.4 69.8]
   [57.2 77. ]]]


 [[[59.  86. ]
   [48.2 68. ]
   [59.  80.6]
   [59.  73.4]
   [44.6 73.4]
   [59.  86. ]
   [55.4 80.6]]

  [[48.2 82.4]
   [57.2 68. ]
   [42.8 69.8]
   [57.2 77. ]
   [51.8 69.8]
   [57.2 69.8]
   [50.  68. ]]

  [[44.6 82.4]
   [42.8 80.6]
   [51.8 80.6]
   [51.8 68. ]
   [55.4 71.6]
   [59.  68. ]
   [55.4 80.6]]

  [[51.8 73.4]
   [51.8 78.8]
   [51.8 69.8]
   [59.  78.8]
   [48.2 69.8]
   [53.6 87.8]
   [42.8 75.2]]]


 [[[41.  66.2]
   [44.6 66.2]
   [46.4 68. ]
   [42.8 66.2]
   [37.4 69.8]
   [41.  44.6]
   [66.2 35.6]]

  

In [44]:
#q20 Sort the above data in descending order on the basis of weekly average for the month of Dec
a=np.mean(temp[1::4,0::4,:,:])
b=np.mean(temp[1::4,1::4,:,:])
c=np.mean(temp[1::4,2::4,:,:])
d=np.mean(temp[1::4,3::4,:,:])
arr=np.array([a,b,c,d])
arr[::-1].sort()
print(arr)



[19.21428571 17.64285714 17.64285714 16.71428571]


In [45]:
#q22 Create an array that stores the difference between the min and max temp for each day in all the winter month
a=temp[:,:,:,1:]
b=temp[:,:,:,0::2]
c=a-b
print("difference between max and min temp:\n",c)

difference between max and min temp:
 [[[[ 22]
   [ 23]
   [ 19]
   [  7]
   [ 18]
   [  6]
   [  6]]

  [[ 16]
   [ 19]
   [ 23]
   [ 10]
   [ 24]
   [ 15]
   [ 19]]

  [[  8]
   [ 13]
   [ 22]
   [ 23]
   [ 12]
   [ 15]
   [ 14]]

  [[ 23]
   [ 22]
   [ 25]
   [ 25]
   [ 18]
   [  8]
   [ 11]]]


 [[[ 15]
   [ 11]
   [ 12]
   [  8]
   [ 16]
   [ 15]
   [ 14]]

  [[ 19]
   [  6]
   [ 15]
   [ 11]
   [ 10]
   [  7]
   [ 10]]

  [[ 21]
   [ 21]
   [ 16]
   [  9]
   [  9]
   [  5]
   [ 14]]

  [[ 12]
   [ 15]
   [ 10]
   [ 11]
   [ 12]
   [ 19]
   [ 18]]]


 [[[ 14]
   [ 12]
   [ 12]
   [ 13]
   [ 18]
   [  2]
   [-17]]

  [[ 18]
   [ 15]
   [ 14]
   [ 19]
   [ 12]
   [ -3]
   [-15]]

  [[ 12]
   [ 17]
   [ 17]
   [ 13]
   [ 13]
   [  1]
   [-16]]

  [[ 16]
   [ 13]
   [ 17]
   [ 14]
   [ 14]
   [ -5]
   [-13]]]


 [[[ 15]
   [ 13]
   [ 29]
   [ 11]
   [  8]
   [ 19]
   [-14]]

  [[ 11]
   [  8]
   [ 11]
   [ 10]
   [  7]
   [ -4]
   [-13]]

  [[  9]
   [  8]
   [ 14]
   [  9]
   [ 10]
 